docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - { 'Overview and Features': features.md }
    - { 'Quick Start': quick-start.md }
    - { Applications: application.md }
    - { Containers: [{ Introduction: container/intro.md }, { 'Container Factories': container/factories.md }, { 'Using laminas-servicemanager': container/laminas-servicemanager.md }, { 'Using Pimple': container/pimple.md }, { 'Using Aura.Di': container/aura-di.md }] }
    - { 'Routing Adapters': [{ Introduction: router/intro.md }, { 'Routing Interface': router/interface.md }, { 'URI Generation': router/uri-generation.md }, { 'Routing vs Piping': router/piping.md }, { 'Using Aura': router/aura.md }, { 'Using FastRoute': router/fast-route.md }, { 'Using the Laminas Router': router/laminas-router.md }] }
    - { Templating: [{ Introduction: template/intro.md }, { 'Template Interface': template/interface.md }, { 'Templated Middleware': template/middleware.md }, { 'Using Plates': template/plates.md }, { 'Using Twig': template/twig.md }, { 'Using laminas-view': template/laminas-view.md }] }
    - { 'Error Handling': error-handling.md }
    - { Emitters: emitters.md }
    - { Examples: usage-examples.md }
    - { Cookbook: cookbook.md }
site_name: mezzio
site_description: 'mezzio: PSR-7 Middleware Microframework'
repo_url: 'https://github.com/mezzio/mezzio'
