docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - { 'Overview and Features': features.md }
    - { 'Quick Start: Skeleton + Installer': quick-start-skeleton.md }
    - { 'Quick Start: Standalone': quick-start.md }
    - { Applications: application.md }
    - { Containers: [{ Introduction: container/intro.md }, { 'Container Factories': container/factories.md }, { 'Using laminas-servicemanager': container/laminas-servicemanager.md }, { 'Using Pimple': container/pimple.md }, { 'Using Aura.Di': container/aura-di.md }] }
    - { 'Routing Adapters': [{ Introduction: router/intro.md }, { 'Routing Interface': router/interface.md }, { 'URI Generation': router/uri-generation.md }, { 'Route Result Observers': router/result-observers.md }, { 'Routing vs Piping': router/piping.md }, { 'Using Aura': router/aura.md }, { 'Using FastRoute': router/fast-route.md }, { 'Using the Laminas Router': router/laminas-router.md }] }
    - { Templating: [{ Introduction: template/intro.md }, { 'Template Renderer Interface': template/interface.md }, { 'Templated Middleware': template/middleware.md }, { 'Using Plates': template/plates.md }, { 'Using Twig': template/twig.md }, { 'Using laminas-view': template/laminas-view.md }] }
    - { 'Error Handling': error-handling.md }
    - { Helpers: [{ Introduction: helpers/intro.md }, { UrlHelper: helpers/url-helper.md }, { ServerUrlHelper: helpers/server-url-helper.md }] }
    - { Emitters: emitters.md }
    - { Examples: usage-examples.md }
    - { Cookbook: [{ 'Prepending common path to all routes': cookbook/common-prefix-for-routes.md }, { 'Route-specific middleware pipeline': cookbook/route-specific-pipeline.md }, { 'Setting custom 404 page handling': cookbook/custom-404-page-handling.md }, { 'Registering custom view helpers for using laminas-view': cookbook/using-custom-view-helpers.md }, { 'Using laminas-form view helpers': cookbook/using-laminas-form-view-helpers.md }] }
site_name: mezzio
site_description: 'mezzio: PSR-7 Middleware Microframework'
repo_url: 'https://github.com/mezzio/mezzio'
